### ISSUE TITLE
[Issue#12] Бессмысленная строка кода

### ISSUE THREAD

**Issue by IvanYarochkin** [WildQnex/FlowerShop#12]
![1](https://user-images.githubusercontent.com/28692548/28391257-f1fdb448-6ce5-11e7-8b3d-92dfb8067267.JPG)

**Comment by xxMikhailx** [comment]
В этом дне примере после твоего выделения следующие две строки тоже можно объединить, не знаю зачем их разделять здесь, получится так:
Accessory accessory = new Accessory("Обертка", 0.7);
