### ISSUE TITLE
[Issue #19] Не вижу разницы между GardenFlower от FieldFlower

### ISSUE THREAD

**Issue by IvanYarochkin** [WildQnex/FlowerShop#19]
Два класса имеют одну и ту же переменную, обозначающую одно и то же, в чем их разница?

![6](https://user-images.githubusercontent.com/28692548/28463795-f6a28c58-6e2a-11e7-9add-85513624a7c1.JPG)
![7](https://user-images.githubusercontent.com/28692548/28463796-f6c15ade-6e2a-11e7-96d4-114837f94e03.JPG)

**Comment by WildQnex** [comment]
Это все относится к 5 проблеме
