### ISSUE TITLE
[Issue 25] Попробуй сам реализовать метод compare в интерфейсе Comparator

### ISSUE THREAD

**Issue by IvanYarochkin** [WildQnex/FlowerShop#25]
То, как ты сделал - не ошибка, но было бы неплохо тебе и так научиться делать.

**Comment by WildQnex** [comment]
Я его сделал сам но прикол в том что нажал alt+enter он его заменил

**Comment by xxMikhailx** [comment]
Да, это точно, компаратор нужно самому реализовать, не обращай внимания в этом случае на то, что идея предлагает, то что тут идея за тебя сделала сложная штука, не стоит сейчас её использовать.
